#!/usr/bin/env python3
"""Generate a quick code->doc map by grepping obvious keywords.

This is a helper for maintainers; it produces `references/CODE_MAP.md` suggestions.
"""
import re
from pathlib import Path

# Find repository root by walking up until we find 'run.py' or '.git'
ROOT = Path(__file__).resolve()
for _ in range(6):
    ROOT = ROOT.parent
    if (ROOT / "run.py").exists() or (ROOT / ".git").exists():
        break
DOCS = ROOT / "docs" / "training_lifecycle"
OUT = ROOT / ".claude" / "skills" / "training-lifecycle" / "references" / "CODE_MAP.md"

# naive mapping of chapter file to keywords to search for
mapping = {
    "01-ui-job-creation.md": ["ui/", "JobForm", "createJob"],
    "02-prisma-and-db.md": ["prisma", "Prisma"],
    "03-worker-scheduling.md": ["cron", "spawn_worker", "schedule"],
    "04-run-py-and-job-loader.md": ["run.py", "JobLoader", "load_job"],
    "05-pipeline-and-jobs.md": ["StableDiffusion", "model_utils", "Pipeline"],
    "06-pretraining-setup.md": ["dataloader_mixins", "auto_crop_to_bucket", "DatasetConfig"],
    "07-training-loop.md": ["train_step", "optimizer", "EMA"],
    "08-checkpoints.md": ["save_checkpoint", "metadata"],
    "09-repro-troubleshoot.md": ["seed", "deterministic"]
}

lines = ["# Code map — training lifecycle\n", "This file was generated by `scripts/index_code_map.py`.\n\n"]

for chapter, keywords in mapping.items():
    lines.append(f"## {chapter}\n")
    hits = []
    for k in keywords:
        # search repo for the keyword
        for p in ROOT.rglob("*.*"):
            if p.is_file() and p.suffix not in {".png", ".jpg", ".jpeg", ".gif", ".pb", ".pt"}:
                try:
                    txt = p.read_text(errors="ignore")
                except Exception:
                    continue
                idx = txt.find(k)
                if idx != -1:
                    # compute 1-based line number of first occurrence
                    line_no = txt.count('\n', 0, idx) + 1
                    rel = p.relative_to(ROOT).as_posix()
                    hits.append((k, f"{rel}:{line_no}"))
    if hits:
        for k, rel in sorted(set(hits)):
            lines.append(f"- keyword `{k}` → `{rel}`\n")
    else:
        lines.append("- (no matches found)\n")
    lines.append("\n")

OUT.write_text("\n".join(lines))
print(f"Wrote {OUT}")
